### ISSUE TITLE
Test 01 in test_WeekdaysInRange.py is failing due to it returning 1 rather than 0.

### ISSUE THREAD

**Issue by ZakBibi** [ZakBibi/PracticePython#47]
```python
    def test_01_same_day(self):
        start = '2018/11/09'
        end = '2018/11/09'
        self.assertEqual(0, weekdays_in_range(start, end))
```

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 30, in _patched_equals
    old(self, first, second, msg)
  File "/Users/hannah/miniconda3/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/hannah/miniconda3/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1
```

**Comment by ZakBibi** [comment]
The problem has been identified. 

```python
def isoweek_day_list(starting_isoweekday_num, num_of_days):
    min_day_num, max_day_num = 1, 7
    lst = [starting_isoweekday_num]

    count = starting_isoweekday_num
    while len(lst) < num_of_days:
        count += 1
        if count > max_day_num:
            count = min_day_num
        lst.append(count)

    return lst
```
In this function the list returned in lst has 1 element in it - [5]. The length of lst therefore is 1. This is later returned here, in weekdays_in_range()

```python

def weekdays_in_range(start_date_str, end_date_str):
    start_date = isoweek_datetime(start_date_str)
    difference = number_of_days_between(start_date_str, end_date_str)

    days_list = isoweek_day_list(start_date, difference)

    days_without_weekends = [d for d in days_list
                             if d != 6 and d != 7]

    return len(days_without_weekends)
```

Therefore test_01 is returning 1 due to the len of days_without_weekends being 1.

**Comment by ZakBibi** [comment]
Problem has been solved. 
By removing what was being added to the list in isoweek_day_list.
